/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.net.perorin.tama.chang

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        expect:
        true
    }
}
